
---
title: "INA Plots"
author: "Bartol Freškura"
date: "September 26, 2015"
output:
      html_document:
            toc: true
---

```{r echo=FALSE}
##SCRIPT FOR CONVERTING DATA FROM SURVEY CSV TO R DATA STRUCTURES

#' @name Convert from csv to data frame
#' @author Bartol Freškura
#' @description Converts raw csv file from survey to a R data structure in a form of data frame
#' @param path Path to folder where .csv files is locatde
#' @param fileName Name of the .csv file
#' @return Data frame with processed data
#' @example convertToRData("/home/username/Documents/Project/CSVDir/", "sample_survey.csv")
convertToRData <- function(path, fileName){
      
      ##CONSTANTS
      #LOCAL path for csv files
      pathCsv <- path
      
      
      #Types of attributes in columns
      columnTypes <- c("character","character","character","integer","integer","integer","integer",
                       "integer", "character", "character", "character", "character", "character", "character"
                       , "character", "character", "character", "character","character","character")
      
      #Column names
      columnNames <- c("ID.Hash","Sex","Age","Student.Status","Employer.Opinion","National.Identity",
                       "Employee.Satisfaction","Future.Employee","Work.Field","Industry","Creativity","Ecology",
                       "Science","Energetics","Croatia","Association.Career", "E.Mail", "Start.Date","End.Date",
                       "Network.ID")
      
      ##Load data
      rawData <- read.csv(paste(pathCsv,fileName, sep = ''),header = TRUE, na.strings = "",
                          colClasses = columnTypes, comment.char = "")
      #Set column names
      colnames(rawData) <- columnNames
      
      
      ##### QUESTION CONSTANTS ############
      
      ##Koja je vaša dobna skupina?*
      #constants
      to17 <- "do 17"
      from18To20 <- "od 18 do 20"
      from21To23 <- "od 21 do 23"
      from23To26 <- "od 24 do 26"
      from27Above <- "27 ili stariji"
      
      
      #Koje područje poslovanja INA grupacije smatrate osobno najzanimljivijim?*
      #constants
      research <- "Istraživanje i proizvodnja nafte i plina"
      rafinery <- "Rafinerije i marketing"
      finance <- "Financije"
      it_sup <- "IT potpora"
      logistics <- "Logistička potpora"
      
      ##### QUESTION CONSTANTS ############
      
      
      #Create vectors for modified data frame
      id <- character()
      sex <- character()
      age <- character()
      student.status <- integer()
      employer.opinion <- integer()
      national.identity <- integer()
      employee.satisfaction <- integer()
      future.employee <- integer()
      work.field <- character()
      ina.association <- character()
      association.career <- character()
      email <- character()
      start.date <- date()
      end.date <- date()
      network.id <- character()
      
      #Iterate through data frame and do the conversion
      
      for (i in 1:nrow(rawData)) {
            #Handle ID hash
            id <- c(id, rawData[i,]$ID.Hash)
            
            #Handle sex (hueuheuhueuhe69)
            if(rawData[i,2]=="muško"){
                  sex <- c(sex,"M")
            }
            else{
                  sex <- c(sex,"F")
            }
            
            #Handle Age
            if(rawData[i,3]==to17){
                  age <- c(age, "0-17")
            }
            else if(rawData[i,3]==from18To20){
                  age <- c(age, "18-20")
            }
            else if(rawData[i,3]==from21To23){
                  age <- c(age, "21-23")
            }
            else if(rawData[i,3]==from23To26){
                  age <- c(age, "24-26")
            }
            else{
                  age <- c(age, "27-Inf")
            }
            
            #Handle student status
            # 1== STUDENT_TRUE, 0== STUDENT_FALSE
            student.status <- c(student.status, rawData[i,]$Student.Status)
            
            #Handle Employer opinion
            employer.opinion <- c(employer.opinion, rawData[i,]$Employer.Opinion)
            
            #Handle National Identity rating
            national.identity <- c( national.identity , rawData[i,]$National.Identity)
            
            #Handle Employee satifaction
            employee.satisfaction <- c(employee.satisfaction, rawData[i,]$Employee.Satisfaction)
            
            #Handle future employee
            future.employee <- c(future.employee, rawData[i,]$Future.Employee)
            
            #Handle Work field
            if(rawData[i,]$Work.Field==it_sup){
                  work.field <- c(work.field, "IT_Support")
            }
            
            else if(rawData[i,]$Work.Field==research){
                  work.field <- c(work.field, "Research_Production_Oil_Gas")
            }
            
            else if(rawData[i,]$Work.Field==finance){
                  work.field <- c(work.field, "Finances")
            }
            
            else if(rawData[i,]$Work.Field==rafinery){
                  work.field <- c(work.field, "Rafinery_Marketing")
            }
            
            else{
                  work.field <- c(work.field, "Logistics")
            }
            
            
            #Handle INA association
            
            #define temp variables
            ind <- toString(rawData[i,]$Industry)
            cre <- toString(rawData[i,]$Creativity)
            eco <- toString(rawData[i,]$Ecology)
            sci <- toString(rawData[i,]$Science)
            en <- toString(rawData[i,]$Energetics)
            cro <- toString(rawData[i,]$Croatia)
            ##MAGIC :D
            newVec <- paste(ind,cre,eco,sci,en,cro, sep = ";")
            newVec <- gsub(pattern = ";NA", x = newVec, replacement = "")
            newVec <- gsub(pattern = ";;", x = newVec, replacement = "")
            newVec <- gsub(pattern = "NA;", x = newVec, replacement = "")
            ina.association <- c(ina.association, newVec)
            
            
            #Handle Association career
            association.career <- c(association.career, rawData[i,]$Association.Career)
            
            #Handle E-mail
            email <- c(email, rawData[i,]$E.Mail)
            
            #Handle Network ID
            network.id <- c(network.id, rawData[i,]$Network.ID)
            
      }
      
      #Store to new data frame
      dataProc <- data.frame(id,sex,age,student.status,employer.opinion,national.identity,employee.satisfaction,
                             future.employee,work.field,ina.association,association.career,email,network.id)
      
      dataProc
}


```


###Load data
```{r}
library(ggplot2)
path <- "/mnt/8C1A960B1A95F286/Bartol_work/INA_Career_LOGO/resources/"
name <- "sample_survey.csv"
data <- convertToRData(path,name)
```

###Plotting Sex

```{r fig.width = 10, fig.height = 7}
plot <- ggplot(data = data, aes(x=sex, fill=sex)) + coord_cartesian(ylim=c(0,nrow(data)))
plot <- plot + geom_bar(width=0.5) + xlab("Sex") + ylab("Count")
plot <- plot + theme(axis.text=element_text(size=17), axis.title=element_text(size=17))
plot <- plot + scale_fill_discrete(name="Sex", breaks=c("F", "M"), labels=c("Female", "Male"))
plot <- plot + scale_x_discrete(breaks=NULL)

plot
```


###Plotting Age

```{r fig.width = 10, fig.height = 7}
plot <- ggplot(data = data, aes(x=age, fill=age)) + coord_cartesian(ylim=c(0,nrow(data)))
plot <- plot + geom_bar(width=0.5) + xlab("Age") + ylab("Count")
plot <- plot + theme(axis.text=element_text(size=17), axis.title=element_text(size=17))
plot <- plot + scale_fill_discrete(name="Age", breaks=c("0-17", "18-20","21-23","24-26","27-Inf"), 
                                   labels=c ("17 and below", "18 to 20", "21 to 23", "24 to 26", "27 or more"))
plot <- plot + scale_x_discrete(breaks=NULL)

plot
```


###Plotting Student status

```{r fig.width = 10, fig.height = 7}
plot <- ggplot(data = data, aes(x=as.factor(student.status), fill=as.factor(student.status))) + coord_cartesian(ylim=c(0,nrow(data)))
plot <- plot + geom_bar(width=0.5) + xlab("Student status") + ylab("Count")
plot <- plot + theme(axis.text=element_text(size=17), axis.title=element_text(size=17))
plot <- plot + scale_fill_discrete(name="Sex", breaks=c(1, 0), labels=c("Student", "Not Student"))
plot <- plot + scale_x_discrete(breaks=NULL)

plot
```



###Plotting Employer opinion

```{r fig.width = 10, fig.height = 7}
plot <- ggplot(data = data, aes(x=as.factor(employer.opinion))) + coord_cartesian(ylim=c(0,nrow(data)*0.6))
plot <- plot + geom_bar(width=0.5, fill="deepskyblue3") + xlab("Employer rating") + ylab("Count")
plot <- plot + theme(axis.text=element_text(size=17), axis.title=element_text(size=17))

plot
```


###Plotting National identity

```{r fig.width = 10, fig.height = 7}
plot <- ggplot(data = data, aes(x=as.factor(national.identity))) + coord_cartesian(ylim=c(0,nrow(data)*0.40))
plot <- plot + geom_bar(width=0.5, fill="deepskyblue3") + xlab("National Identity rating") + ylab("Count")
plot <- plot + theme(axis.text=element_text(size=17), axis.title=element_text(size=17))

plot
```


###Plotting Employee satisfaction

```{r fig.width = 10, fig.height = 7}
plot <- ggplot(data = data, aes(x=as.factor(employee.satisfaction), fill=as.factor(employee.satisfaction))) + coord_cartesian(ylim=c(0,nrow(data)))
plot <- plot + geom_bar(width=0.5) + xlab("Yes or no") + ylab("Count")
plot <- plot + theme(axis.text=element_text(size=17), axis.title=element_text(size=17))
plot <- plot + scale_fill_discrete(name="", breaks=c(1, 0), labels=c("Yes", "No"))
plot <- plot + scale_x_discrete(breaks=NULL)
plot
```



###Plotting Future employee

```{r fig.width = 10, fig.height = 7}
plot <- ggplot(data = data, aes(x=as.factor(future.employee), fill=as.factor(future.employee))) + coord_cartesian(ylim=c(0,nrow(data)))
plot <- plot + geom_bar(width=0.5) + xlab("Yes or no") + ylab("Count")
plot <- plot + theme(axis.text=element_text(size=17), axis.title=element_text(size=17))
plot <- plot + scale_fill_discrete(name="", breaks=c(1, 0), labels=c("Yes", "No"))
plot <- plot + scale_x_discrete(breaks=NULL)
plot
```


###Plotting Work field

```{r fig.width = 10, fig.height = 7}

plot <- ggplot(data = data, aes(x=work.field, fill=work.field)) + coord_cartesian(ylim=c(0,nrow(data)*0.45))
plot <- plot + geom_bar(width=0.5) + xlab("Field of work") + ylab("Count")
plot <- plot + theme(axis.text=element_text(size=17), axis.title=element_text(size=17))
plot <- plot + scale_fill_discrete(name="Field of work", breaks=c("Finances","IT_Support", "Logistics","Rafinery_Marketing","Research_Production_Oil_Gas"), 
                                   labels=c("Finances", "IT Support", "Logistics", "Rafinery or Marketing",
                                            "Research and production of\n Oil and Gas"))
plot <- plot + scale_x_discrete(breaks=NULL)

plot
```


###Plotting INA Association


```{r echo=FALSE}
#Etracting levels into seperate categories
industry <- character()
creativity <- character()
ecology <- character()
science <- character()
energetics <- character()
croatia <- character()

for(i in 1:nrow(data)){
      #split values into list
      tempList <- strsplit(x=as.character(data[i,]$ina.association), split = ';')
      
      #convert to vector
      tempVec <- unlist(tempList)
      for(j in 1:length(tempVec)){
            if(tempVec[j]=="Kreativnost"){
                  creativity <- c(creativity,tempVec[j])
            }
            else if(tempVec[j]=="Industrija"){
                  industry <- c(industry,tempVec[j])
            }
            else if(tempVec[j]=="Energetika"){
                  energetics <- c(energetics,tempVec[j])
            }
            else if(tempVec[j]=="Ekologija"){
                  ecology <- c(ecology,tempVec[j])
            }
            else if(tempVec[j]=="Znanost"){
                  science <- c(science,tempVec[j])
            }
            else{
                  croatia <- c(croatia,tempVec[j])
            }
      }
      
}


#create new data frame
unifiedVector <- c(industry,croatia,creativity,ecology,science,energetics)
frameINAAssociation <- data.frame(unifiedVector)
colnames(frameINAAssociation) <- c("ina.association")
```


#### Plot
```{r fig.width = 10, fig.height = 7}

plot <- ggplot(data = frameINAAssociation, aes(x=ina.association, fill=ina.association)) + coord_cartesian(ylim=c(0,nrow(frameINAAssociation)*0.5))
plot <- plot + geom_bar(width=0.5) + xlab("INA Association") + ylab("Count")
plot <- plot + theme(axis.text=element_text(size=17), axis.title=element_text(size=17))
plot <- plot + scale_fill_discrete(name="Associations", breaks=c("Ekologija","Energetika", "Hrvatska","Industrija","Kreativnost","Znanost"), 
                                   labels=c("Ecology", "Energetics", "Croatia", "Industry",
                                            "Creativity","Science"))
plot <- plot + scale_x_discrete(breaks=NULL)

plot
```

